{{- if and .Values.botToken (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-bot-token
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  bot_token: {{ .Values.botToken | quote }}
{{- end }}
