#!/usr/bin/env python3
"""Checker for docs/specs/welcome-m1-test-gaps.md.

  mutants [ID ...]  every listed (default: all 13) surviving mutant of the
                    welcome-m1 mutation run must be killed by ITS new test:
                    the test passes on the clean tree, fails on the mutant
                    with an assertion reported inside its own function body.
                    The mutation is applied in place and always rolled back
                    (bytes and sha256 restored, even after a crash: a backup
                    under .git/ is restored on the next start).
  comment           the applyLLMDefaults doc comment sits above its function,
                    and config.go differs from BASE only by that move.
  scope             only allowed files changed, test files only gained lines,
                    spec files untouched, tree clean.

rc=0 means the criterion holds. Do not edit this file: it is part of the spec.
"""
import fcntl
import hashlib
import os
import re
import signal
import subprocess
import sys

BASE = "0a2c9fe004467104465c727cd95979d7cf68ff24"
ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True,
                      text=True, check=True).stdout.strip()
os.chdir(ROOT)
GITDIR = subprocess.run(["git", "rev-parse", "--absolute-git-dir"], capture_output=True,
                        text=True, check=True).stdout.strip()
LOCK = os.path.join(GITDIR, "welcome-test-gaps-mutation.lock")
BACKUP_DIR = os.path.join(GITDIR, "welcome-test-gaps-backup")
SELF = "docs/specs/checks/welcome_m1_test_gaps_check.py"
SPEC_FILES = [SELF, "docs/specs/welcome-m1-test-gaps.md", "docs/spec-queue.md"]
TEST_FILES = [
    "internal/telegram/ephemeral_test.go",
    "internal/telegram/join_test.go",
    "internal/config/welcome_test.go",
    "internal/store/welcome_test.go",
    "internal/watch/welcome_test.go",
]
CONFIG = "internal/config/config.go"

# mutant -> (test file, test function that must kill it)
KILLERS = {
    "M10": ("internal/telegram/ephemeral_test.go", "TestSendEphemeralWrapsDeleteError"),
    "M78": ("internal/telegram/ephemeral_test.go", "TestSendEphemeralDeletesExactFallbackID"),
    "M17": ("internal/telegram/join_test.go", "TestJoinRejectsZeroUserID"),
    "M30": ("internal/config/welcome_test.go", "TestWelcomeForTrimsGlobalText"),
    "M38": ("internal/config/welcome_test.go", "TestWelcomeChatTextAtLimit"),
    "M49": ("internal/store/welcome_test.go", "TestWelcomedRepeatMarkKeepsOneRow"),
    "M62": ("internal/watch/welcome_test.go", "TestWelcomerRateCapInsideWindow"),
    "M63": ("internal/watch/welcome_test.go", "TestWelcomerRateCapWindowEdge"),
    "M64": ("internal/watch/welcome_test.go", "TestWelcomerRateCapWindowEdge"),
    "M72": ("internal/watch/welcome_test.go", "TestWelcomerNotAdmittedBeforeDisabled"),
    "M73": ("internal/watch/welcome_test.go", "TestWelcomerDisabledBeforeChatRow"),
    "M74": ("internal/watch/welcome_test.go", "TestWelcomerChatRowBeforeBlocklist"),
    "M76": ("internal/watch/welcome_test.go", "TestWelcomerKnownBeforeRateCap"),
}

# mutant -> (production file, exact fragment, mutated fragment); taken
# verbatim from the diffs in mutation-report.json of the welcome-m1 run.
MUTATIONS = {
    'M10': (
        'internal/telegram/livept.go',
        '\t\t\treturn 0, fmt.Errorf("%w: %w", ErrEphemeralNotHonored, delErr)\n',
        '\t\t\treturn 0, fmt.Errorf("%w: %v", ErrEphemeralNotHonored, delErr)\n',
    ),
    'M17': (
        'internal/telegram/join.go',
        '\tif !ok || user.IsBot || user.ID == 0 {\n',
        '\tif !ok || user.IsBot {\n',
    ),
    'M30': (
        'internal/config/config.go',
        '\ttext = strings.TrimSpace(w.Text)\n',
        '\ttext = w.Text\n',
    ),
    'M38': (
        'internal/config/config.go',
        '\t\tif n := utf8.RuneCountInString(strings.TrimSpace(chat.Text)); n > telegramMessageRunes {\n',
        '\t\tif n := utf8.RuneCountInString(strings.TrimSpace(chat.Text)); n >= telegramMessageRunes {\n',
    ),
    'M49': (
        'internal/store/migrate.go',
        "\tcreated_at INTEGER NOT NULL DEFAULT (strftime('%s','now')),\n\tPRIMARY KEY(chat_id, user_id)\n",
        "\tcreated_at INTEGER NOT NULL DEFAULT (strftime('%s','now'))\n",
    ),
    'M62': (
        'internal/watch/welcome.go',
        'const welcomeWindow = 60 * time.Second\n',
        'const welcomeWindow = 59 * time.Second\n',
    ),
    'M63': (
        'internal/watch/welcome.go',
        'const welcomeWindow = 60 * time.Second\n',
        'const welcomeWindow = 61 * time.Second\n',
    ),
    'M64': (
        'internal/watch/welcome.go',
        '\t\tif ts.After(cutoff) {\n',
        '\t\tif !ts.Before(cutoff) {\n',
    ),
    'M72': (
        'internal/watch/welcome.go',
        '\tif !telegram.RegisteredChat(cfg, ev.ChatID) {\n\t\treturn OutcomeSkipNotAdmitted, nil\n\t}\n\ttext, on := cfg.Welcome.For(ev.ChatID)\n\tif !on {\n\t\treturn OutcomeSkipDisabled, nil\n',
        '\ttext, on := cfg.Welcome.For(ev.ChatID)\n\tif !on {\n\t\treturn OutcomeSkipDisabled, nil\n\t}\n\tif !telegram.RegisteredChat(cfg, ev.ChatID) {\n\t\treturn OutcomeSkipNotAdmitted, nil\n',
    ),
    'M73': (
        'internal/watch/welcome.go',
        '\ttext, on := cfg.Welcome.For(ev.ChatID)\n\tif !on {\n\t\treturn OutcomeSkipDisabled, nil\n\t}\n\trow, found, err := w.Store.GetChat(ev.ChatID)\n\tif err != nil {\n\t\treturn OutcomeError, err\n\t}\n\tif found && !row.Enabled {\n\t\treturn OutcomeSkipChatDisabled, nil\n',
        '\trow, found, err := w.Store.GetChat(ev.ChatID)\n\tif err != nil {\n\t\treturn OutcomeError, err\n\t}\n\tif found && !row.Enabled {\n\t\treturn OutcomeSkipChatDisabled, nil\n\t}\n\ttext, on := cfg.Welcome.For(ev.ChatID)\n\tif !on {\n\t\treturn OutcomeSkipDisabled, nil\n',
    ),
    'M74': (
        'internal/watch/welcome.go',
        '\trow, found, err := w.Store.GetChat(ev.ChatID)\n\tif err != nil {\n\t\treturn OutcomeError, err\n\t}\n\tif found && !row.Enabled {\n\t\treturn OutcomeSkipChatDisabled, nil\n\t}\n\tif w.Blocklist != nil && w.Blocklist.Listed(ev.UserID) {\n\t\treturn OutcomeSkipBlocklisted, nil\n',
        '\tif w.Blocklist != nil && w.Blocklist.Listed(ev.UserID) {\n\t\treturn OutcomeSkipBlocklisted, nil\n\t}\n\trow, found, err := w.Store.GetChat(ev.ChatID)\n\tif err != nil {\n\t\treturn OutcomeError, err\n\t}\n\tif found && !row.Enabled {\n\t\treturn OutcomeSkipChatDisabled, nil\n',
    ),
    'M76': (
        'internal/watch/welcome.go',
        '\tknown, err := w.Store.WasWelcomed(ev.ChatID, ev.UserID)\n\tif err != nil {\n\t\treturn OutcomeError, err\n\t}\n\tif known {\n\t\treturn OutcomeSkipKnown, nil\n\t}\n\ttrust, err := w.Store.TrustCount(ev.ChatID, ev.UserID)\n\tif err != nil {\n\t\treturn OutcomeError, err\n\t}\n\tif trust > 0 {\n\t\treturn OutcomeSkipKnown, nil\n\t}\n\tmax := 20\n\tif cfg.Welcome.MaxPerMinute != nil {\n\t\tmax = *cfg.Welcome.MaxPerMinute\n\t}\n\tnow := w.now()\n\tif w.rateCapped(ev.ChatID, now, max) {\n\t\treturn OutcomeSkipRateCapped, nil\n',
        '\tmax := 20\n\tif cfg.Welcome.MaxPerMinute != nil {\n\t\tmax = *cfg.Welcome.MaxPerMinute\n\t}\n\tnow := w.now()\n\tif w.rateCapped(ev.ChatID, now, max) {\n\t\treturn OutcomeSkipRateCapped, nil\n\t}\n\tknown, err := w.Store.WasWelcomed(ev.ChatID, ev.UserID)\n\tif err != nil {\n\t\treturn OutcomeError, err\n\t}\n\tif known {\n\t\treturn OutcomeSkipKnown, nil\n\t}\n\ttrust, err := w.Store.TrustCount(ev.ChatID, ev.UserID)\n\tif err != nil {\n\t\treturn OutcomeError, err\n\t}\n\tif trust > 0 {\n\t\treturn OutcomeSkipKnown, nil\n',
    ),
    'M78': (
        'internal/telegram/livept.go',
        '\t\tif delErr := p.DeleteMessages(ctx, chat, []int{sent.messageID}); delErr != nil {\n',
        '\t\tif delErr := p.DeleteMessages(ctx, chat, []int{sent.messageID + 100}); delErr != nil {\n',
    ),
}

LLM_COMMENT = [
    "// applyLLMDefaults fills LLM fields left unset. Enabled defaults to FALSE",
    "// (external calls are opt-in), so — unlike the other blocks — a nil Enabled",
    "// stays disabled.",
]
WELCOME_COMMENT = [
    "// applyWelcomeDefaults fills Welcome fields left unset. Enabled defaults",
    "// to false (a greeting is opt-in) and MaxPerMinute to 20. An explicit",
    "// value, including false and 0, is left alone so Validate can reject 0.",
]


def git(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True)


def fail(msg):
    print("FAIL:", msg)
    return 1


def sha(b):
    return hashlib.sha256(b).hexdigest()


def func_span(path, name):
    """1-based (first, last) lines of `func name(` ... closing `}`."""
    lines = open(path, encoding="utf-8").read().split("\n")
    start = None
    for i, line in enumerate(lines):
        if line.startswith("func " + name + "("):
            if start is not None:
                return None
            start = i
    if start is None:
        return None
    for j in range(start + 1, len(lines)):
        if lines[j] == "}":
            return start + 1, j + 1
    return None


def existed_at_base(path, name):
    r = git("show", BASE + ":" + path)
    return r.returncode == 0 and re.search(r"^func " + re.escape(name) + r"\(", r.stdout, re.M)


def go_test(pkg, names):
    pattern = "^(" + "|".join(sorted(set(names))) + ")$"
    cmd = ["./scripts/dev.sh", "test", "-count=1", "-v", "-run", pattern, "./" + pkg + "/"]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
    return r.returncode, r.stdout + r.stderr


def restore_leftovers():
    if not os.path.isdir(BACKUP_DIR):
        return
    for dirpath, _, files in os.walk(BACKUP_DIR):
        for f in files:
            src = os.path.join(dirpath, f)
            rel = os.path.relpath(src, BACKUP_DIR)
            with open(src, "rb") as fh:
                data = fh.read()
            with open(rel, "wb") as fh:
                fh.write(data)
            os.remove(src)
            print(f"restored {rel} left mutated by an interrupted run")
    for dirpath, _, _ in sorted(os.walk(BACKUP_DIR), reverse=True):
        os.rmdir(dirpath)


def interrupted(signum, frame):
    raise KeyboardInterrupt(f"signal {signum}")


def check_mutant(mid):
    target, old, new = MUTATIONS[mid]
    test_file, test_name = KILLERS[mid]
    pkg = os.path.dirname(test_file)
    if existed_at_base(test_file, test_name):
        return fail(f"{mid}: {test_name} already existed at BASE, it must be a new test")
    span = func_span(test_file, test_name)
    if span is None:
        return fail(f"{mid}: no single `func {test_name}(` in {test_file}")
    rc, out = go_test(pkg, [test_name])
    if rc != 0 or not re.search(r"^--- PASS: " + re.escape(test_name) + r" \(", out, re.M):
        print(out[-3000:])
        return fail(f"{mid}: {test_name} is not green on the clean tree (rc={rc})")
    with open(target, "rb") as fh:
        orig = fh.read()
    orig_sha = sha(orig)
    text = orig.decode("utf-8")
    if text.count(old) != 1:
        return fail(f"{mid}: fragment occurs {text.count(old)} times in {target}, need exactly 1")
    backup = os.path.join(BACKUP_DIR, target)
    os.makedirs(os.path.dirname(backup), exist_ok=True)
    with open(backup, "wb") as fh:
        fh.write(orig)
    try:
        with open(target, "wb") as fh:
            fh.write(text.replace(old, new, 1).encode("utf-8"))
        if git("diff", "--quiet", "--", target).returncode == 0 and \
                git("diff", "--quiet", BASE, "--", target).returncode == 0:
            return fail(f"{mid}: mutation did not land in {target}")
        rc, out = go_test(pkg, [test_name])
    finally:
        with open(target, "wb") as fh:
            fh.write(orig)
        os.remove(backup)
        with open(target, "rb") as fh:
            back = sha(fh.read())
        if back != orig_sha:
            print(f"FAIL: {mid}: {target} sha256 after restore {back} != {orig_sha}")
            sys.exit(3)
    if "[build failed]" in out or "[setup failed]" in out:
        print(out[-3000:])
        return fail(f"{mid}: mutant did not compile, nothing proven")
    if rc == 0 or not re.search(r"^--- FAIL: " + re.escape(test_name) + r" \(", out, re.M):
        return fail(f"{mid}: SURVIVED — {test_name} passes on the mutant (rc={rc})")
    base = os.path.basename(test_file)
    hits = [(int(n), line.strip()) for line in out.splitlines()
            for m in [re.match(r"^\s+" + re.escape(base) + r":(\d+): ", line)] if m
            for n in [m.group(1)]]
    own = [h for h in hits if span[0] <= h[0] <= span[1]]
    if not own:
        print(out[-3000:])
        return fail(f"{mid}: {test_name} failed, but no assertion reported inside "
                    f"{base}:{span[0]}-{span[1]} (got {[h[0] for h in hits]})")
    print(f"{mid}: killed by {test_name} — {own[0][1][:160]}")
    return 0


def cmd_mutants(ids):
    ids = ids or list(MUTATIONS)
    unknown = [i for i in ids if i not in MUTATIONS]
    if unknown:
        return fail(f"unknown mutants {unknown}")
    for sig in (signal.SIGTERM, signal.SIGHUP, signal.SIGINT):
        signal.signal(sig, interrupted)
    with open(LOCK, "w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        restore_leftovers()
        failed = [mid for mid in ids if check_mutant(mid) != 0]
    if failed:
        return fail(f"not killed: {failed}")
    print(f"all {len(ids)} mutants killed")
    return 0


def changed_lines(path):
    r = git("diff", "-U0", BASE, "--", path)
    removed, added = [], []
    for line in r.stdout.splitlines():
        if line.startswith("---") or line.startswith("+++"):
            continue
        if line.startswith("-"):
            removed.append(line[1:])
        elif line.startswith("+"):
            added.append(line[1:])
    return removed, added


def cmd_comment():
    lines = open(CONFIG, encoding="utf-8").read().split("\n")

    def above(func_line):
        idx = [i for i, l in enumerate(lines) if l == func_line]
        if len(idx) != 1:
            return None, None
        return lines[idx[0] - 3:idx[0]], lines[idx[0] - 4]

    llm, _ = above("func (c *Config) applyLLMDefaults() {")
    if llm != LLM_COMMENT:
        return fail(f"applyLLMDefaults is not directly preceded by its comment: {llm}")
    wel, before = above("func (c *Config) applyWelcomeDefaults() {")
    if wel != WELCOME_COMMENT or before.startswith("//"):
        return fail(f"applyWelcomeDefaults comment block is not exactly its own: {before!r} + {wel}")
    removed, added = changed_lines(CONFIG)
    rm = sorted(l for l in removed if l.strip())
    ad = sorted(l for l in added if l.strip())
    if rm != sorted(LLM_COMMENT) or ad != sorted(LLM_COMMENT):
        return fail(f"{CONFIG} changed beyond the comment move: -{rm} +{ad}")
    print("comment moved, config.go otherwise identical to BASE")
    return 0


def cmd_scope():
    spec_commit = git("log", "--diff-filter=A", "--format=%H", "-1", "--", SELF).stdout.strip()
    if not spec_commit:
        return fail("spec commit not found")
    r = git("diff", "--name-only", BASE + "..HEAD")
    changed = [l for l in r.stdout.splitlines() if l]
    allowed = set(TEST_FILES) | {CONFIG} | set(SPEC_FILES)
    extra = [f for f in changed if f not in allowed]
    if extra:
        return fail(f"files outside the milestone changed: {extra}")
    if git("diff", "--quiet", spec_commit, "HEAD", "--", *SPEC_FILES).returncode != 0:
        return fail(f"spec files differ from spec commit {spec_commit[:12]}")
    for line in git("diff", "--numstat", BASE + "..HEAD", "--", *TEST_FILES).stdout.splitlines():
        add, dele, path = line.split("\t")
        if dele != "0":
            return fail(f"{path}: {dele} existing lines removed or changed, only additions allowed")
    dirty = git("status", "--porcelain", "--", ".", ":(exclude)report.json",
                ":(exclude)report-blocked.md", ":(exclude)tmp").stdout.strip()
    if dirty:
        return fail(f"tree not clean:\n{dirty}")
    print("scope ok:", ", ".join(changed))
    return 0


def main(argv):
    if not argv or argv[0] not in ("mutants", "comment", "scope"):
        print(__doc__)
        return 2
    if git("cat-file", "-e", BASE + "^{commit}").returncode != 0:
        return fail(f"BASE {BASE} not in this repository")
    if argv[0] == "mutants":
        return cmd_mutants(argv[1:])
    if argv[0] == "comment":
        return cmd_comment()
    return cmd_scope()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
